spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database:3306/campinity
    username: server
    password: ssafy123!

  jpa:
    hibernate:
      ddl-auto: none